version: '2.3'

services:
  web:
    build:
      context: .
    depends_on:
      - db
    volumes:
      - .:/task_manager
      - 'b_cache:/bundle_cache:rw'
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      BUNDLE_PATH: /bundle_cache
  db:
    image: postgres:10.3-alpine
volumes:
  b_cache: