version: '2.0'

services:
  web:
    build:
      context: .
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - "3000:3000"
  db:
    image: postgres:10.3-alpine
    volumes:
      - ./../db/data:/var/lib/postgresql/data